### ISSUE TITLE
const qualifier for arrays with your assets is missing

### ISSUE THREAD

**Issue by untoxa** [ty-porter/pocket-league#7]
i noticed, that const qualifier for arrays with your assets is missing. that leads to generation of enormous initialization code (size of your array multiplied by 5) into your ROM, that construct your arrays with graphics data in RAM. that is a waste of ROM as well as RAM. i suggest you to use new updated set of GBTD/GBMB tools from my repo: https://github.com/untoxa/GBTD_GBMB/releases/tag/2.4.4

**Comment by ty-porter** [comment]
Good suggestion. I'll be sure to take a look in the next few days.

**Comment by untoxa** [comment]
i also suggest you to look into /gbdk-2020/examples/gb -- there are lot's of useful examples, say, "metasprites" - demonstrates using of GBDK functions, that allow manipulate each metasprite (sprite that consist of several hardware sprites) as one, and also "large_map" example is of some interest - that demonstrates scrolling of the background maps, that are up to 255 tiles by one of the dimentions.

metasprites: https://github.com/gbdk-2020/gbdk-2020/blob/develop/gbdk-lib/examples/gb/metasprites/metasprites.c 
large_map: https://github.com/gbdk-2020/gbdk-2020/blob/develop/gbdk-lib/examples/gb/large_map/large_map.c

i also suggest you to join GBDK-2020 discord server.

**Comment by untoxa** [comment]
and not to open a new issue, one more suggestion here. you include header-files with code. that is not how C program should be designed according to Feng Shui. for example, GBTD emits *.C file as well as *.H file for each export. to use that in C "properly", you should include *.h file in your main source file, and compile each C file into object, and then link those objects together into ROM-file. that might sound complex, but with GBDK-2020 nothing is easier. you just do:
`lcc -o mygame.gb main.c background.c sprite1.c sprite2.c music.c`
and it does all the magic. look into examples, they are handy.
